### ISSUE TITLE
Icons Not Showing

### ISSUE THREAD

**Issue by AhoyCapn** [okarin001/Onepunch#1]
**Describe the bug**
After installing and applying the Onepunch theme, none of the icons properly show.

**To Reproduce**
1. Open powershell
2. Install with spicetify restore
spicetify config extensions dribbblish.js-
spicetify config current_theme Onepunch
spicetify apply
3. When Spotify opens, none of the icons are properly shown.

**Expected behavior**
I expected all of the icons to be in their proper spots, however, almost all of them have disappeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/47093949/116707047-7d242080-a98b-11eb-89f4-6a9777f81bf9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Version 20H2
 - Spotify Version 1.1.58.820

**Additional context**
I have tried a bunch of other themes, and they all seem to work properly.

**Comment by Elyte06** [comment]
Having the same issue. Feel it could be something to do with Windows

**Comment by okarin001** [comment]
Is the `overwrite_assets` in config.ini set to 1?

**Comment by AhoyCapn** [comment]
> Is the `overwrite_assets` in config.ini set to 1? And have you tried the steps written in the README.md file

overwrite_assets is set to 1 and I attempted the steps in the README.md file. It is still not working 

![image](https://user-images.githubusercontent.com/47093949/118946663-db517d00-b913-11eb-9103-61da8eb7f56b.png)

**Comment by okarin001** [comment]
> overwrite_assets is set to 1 and I attempted the steps in the README.md file. It is still not working

ohh man, (｡╯︵╰｡) I don't have a windows device on hand. I'll check it if I can access one. For now, remove the asset folder from this theme.  

don't forget to do a 
$ `spicetify restore`
$ `spicetify backup apply` 

PS. I've released the new v2 support.
